# Adaptations to make it run on GKE Cluster:
# - added 'hostname' necessary for 'postgres-backup' CronJob
# - populate Values with parameters of Google Cloud DB for Postgres instance
apiVersion: v1
kind: Secret
metadata:
  name: polls-secret
stringData:
  username: pollsuser
  password: pollspass
  dbname: pollsdb
  hostname: polls-db-postgresql
  database_url: postgres://pollsuser:pollspass@polls-db-postgresql/pollsdb
